normalise git reference variables through build and update scripts

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -17,7 +17,7 @@ jobs:
       matrix:
         build:
           # Undeclared release tag finds latest from GitHub tags
-          - {latest: "false", tag: "v2.5.5", python: "3.10", pytorch: "2.4.0"}
+          - {latest: "false", fooocus: "v2.5.5", python: "3.10", pytorch: "2.4.0"}
     steps:
       -
         name: Free Space
@@ -63,21 +63,21 @@ jobs:
         run: |
             img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
             img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cpu"
-            if [[ -z '${{ matrix.build.tag }}' ]]; then
-                FOOOCUS_TAG="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
+            if [[ -z '${{ matrix.build.fooocus }}' ]]; then
+                FOOOCUS_BUILD_REF="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
             else
-                FOOOCUS_TAG="${{ matrix.build.tag }}"
+                FOOOCUS_BUILD_REF="${{ matrix.build.fooocus }}"
             fi
-            [ -z "$FOOOCUS_TAG" ] && { echo "Error: FOOOCUS_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "FOOOCUS_TAG=${FOOOCUS_TAG}" >> ${GITHUB_ENV}
+            [ -z "$FOOOCUS_BUILD_REF" ] && { echo "Error: FOOOCUS_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "FOOOCUS_BUILD_REF=${FOOOCUS_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}"
             fi
             echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -89,7 +89,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cpu-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            FOOOCUS_TAG=${{ env.FOOOCUS_TAG }}
+            FOOOCUS_BUILD_REF=${{ env.FOOOCUS_BUILD_REF }}
           push: true
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
@@ -102,7 +102,7 @@ jobs:
       matrix:
         build:
           # Undeclared release tag finds latest from GitHub tags
-          - {latest: "false", tag: "v2.5.5", python: "3.10", pytorch: "2.4.0", cuda: "12.1.1-base"}
+          - {latest: "false", fooocus: "v2.5.5", python: "3.10", pytorch: "2.4.0", cuda: "12.1.1-base"}
           
     steps:
       -
@@ -150,22 +150,22 @@ jobs:
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
           
-          if [[ -z '${{ matrix.build.tag }}' ]]; then
-                FOOOCUS_TAG="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.fooocus }}' ]]; then
+                FOOOCUS_BUILD_REF="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
             else
-                FOOOCUS_TAG="${{ matrix.build.tag }}"
+                FOOOCUS_BUILD_REF="${{ matrix.build.fooocus }}"
             fi
-            [ -z "$FOOOCUS_TAG" ] && { echo "Error: FOOOCUS_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "FOOOCUS_TAG=${FOOOCUS_TAG}" >> ${GITHUB_ENV}
+            [ -z "$FOOOCUS_BUILD_REF" ] && { echo "Error: FOOOCUS_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "FOOOCUS_BUILD_REF=${FOOOCUS_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path}:latest-cuda"
-                TAGS="${TAGS}, ${img_path_dhub}:${FOOOCUS_TAG}, ${img_path_dhub}:latest"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path}:latest-cuda"
+                TAGS="${TAGS}, ${img_path_dhub}:${FOOOCUS_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}, ${img_path_dhub}:${FOOOCUS_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}, ${img_path_dhub}:${FOOOCUS_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -177,7 +177,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            FOOOCUS_TAG=${{ env.FOOOCUS_TAG }}
+            FOOOCUS_BUILD_REF=${{ env.FOOOCUS_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
@@ -188,7 +188,7 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", tag: "v2.5.5", python: "3.10", pytorch: "2.3.0", rocm: "6.0-core"}
+          - {latest: "false", fooocus: "v2.5.5", python: "3.10", pytorch: "2.3.0", rocm: "6.0-core"}
     steps:
       -
         name: Free Space
@@ -235,21 +235,21 @@ jobs:
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
           
-          if [[ -z '${{ matrix.build.tag }}' ]]; then
-                FOOOCUS_TAG="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.fooocus }}' ]]; then
+                FOOOCUS_BUILD_REF="$(curl -s https://api.github.com/repos/lllyasviel/Fooocus/tags | jq -r '.[0].name')"
             else
-                FOOOCUS_TAG="${{ matrix.build.tag }}"
+                FOOOCUS_BUILD_REF="${{ matrix.build.fooocus }}"
             fi
-            [ -z "$FOOOCUS_TAG" ] && { echo "Error: FOOOCUS_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "FOOOCUS_TAG=${FOOOCUS_TAG}" >> ${GITHUB_ENV}
+            [ -z "$FOOOCUS_BUILD_REF" ] && { echo "Error: FOOOCUS_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "FOOOCUS_BUILD_REF=${FOOOCUS_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${FOOOCUS_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -261,7 +261,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            FOOOCUS_TAG=${{ env.FOOOCUS_TAG }}
+            FOOOCUS_BUILD_REF=${{ env.FOOOCUS_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
